### ISSUE TITLE
Experiment crashes in Microsoft Edge

### ISSUE THREAD

**Issue by smathot** [shyras/osweb#102]
Running the OVP experiment through the Jatos link doesn't work in Microsoft Edge (I annoyingly haven't been able to find the exact version of MS Edge). There's simply a white screen. The version of OSWeb is a bit older (1.0.2) but since I don't think that anything has been done to resolve this in the meantime, I'm posting it as is.

![image](https://user-images.githubusercontent.com/594936/45635928-a166b380-baa6-11e8-93bb-ba95f72146da.png)

**Comment by dschreij** [comment]
Looks like a javascript generation issue. Probably I use an arrow function or spread operator somewhere that Edge doesn't get yet. I'll look into this (hopefully) tomorrow

**Comment by kristian-lange** [comment]
I'm not sure whether this is related but I just discovered a bug in jatos.js that makes it not start the next component in case you do not use jQuery in your study. This should be no problem if you just have one component. I'll fix this asap.

**Comment by smathot** [comment]
Some progress seems to have been made, but it still doesn't work under Edge. I now get a `SCRIPT438: Object doesn't support property or method 'append'` error. This is when launching the OVP or Capybara experiment from osweb.cogsci.nl.

**Comment by dschreij** [comment]
For me these experiments work perfectly using Edge from osweb.cogsci.nl.
I guess there are different versions of Edge floating around after all, or you need to update 😉

**Comment by dschreij** [comment]
If you click the three dots at the top right, go to Settings, and then scroll down, you can find version info on Edge.
I'm using
```
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134
```

**Comment by smathot** [comment]
Right, I'm using

~~~
Microsoft Edge 41.16299.371.0
Microsoft EdgeHTML 16.16299
~~~

Let me check if updating resolves it. (I updated recently though.)

**Comment by dschreij** [comment]
Are you still on Windows 7? or on Windows 10? With the latter, the version of Edge is automatically updated.
Anyway, on https://developer.microsoft.com/en-us/microsoft-edge/platform/changelog/desktop/17134/?compareWith=16299 you can see a (very unclear) version history of Edge. Maybe that will shed some light on this issue.

Alternatively, we can also try to fix this issue for older versions of Edge, but I need your help with that, since I can't reproduce the issue with my versions of Edge anymore. A quick search brought up:

https://stackoverflow.com/questions/15405848/object-doesnt-support-property-or-method-append-in-ie9

So, the problem might be that the variable name `item` is used somewhere in the code, but it has never been declared as a var, giving Edge reason to believe the global var `window.item` is addressed (which only exists in IE/Edge). Could you check if this is the case at the point where this error message is emitted?

**Comment by smathot** [comment]
I'm on Windows 10. I'll check tonight if the issue persists after updating. Probably it won't, and then I feel we can leave the issue as is, because it will affect very few people (and fewer as time progresses).

What would be helpful is a clear minimum requirement: which browsers do we support (and test) and from which versions onward?

**Comment by dschreij** [comment]
Any updates on this? I have not managed to reproduce this issue, but I can't go back versions of Edge. In line with this, it is difficult to test how far back osweb supports browser versions, if you don't install these browser versions yourself. We have already made use of polyfills and such to mimic new operations in older browsers, and according to these polyfills browsers back as far as IE11 should be supported, but is hard to test if this is really the case (except for IE11 of course, which is kind of feature frozen ;) )

**Comment by smathot** [comment]
I haven't managed to upgrade because of too little disk space for the upgrade! But I think we can safely assume that this is a problem related to old versions of Edge, so that it will go away naturally.
