### ISSUE TITLE
Unsupported items do not result in clear error message

### ISSUE THREAD

**Issue by smathot** [shyras/osweb#107]
When you try to load an experiment that has an unsupported item in it, such as `coroutines`, an informative error message appears in the console:

![image](https://user-images.githubusercontent.com/594936/46310233-1960cd80-c5bf-11e8-9afd-1ee593f586ec.png)

However, this error is not visible without opening the console, so for most users this crash seems like a freeze-without-error.

There are various ways in which this could be addressed, either through a message that says that an error message is visible in the console, or by actually showing the error message in the browser. The former solution strikes me as the easiest and sufficient for now. Importantly, this should also work when the experiment is tested standalone or inside Jatos.

**Comment by dschreij** [comment]
Good one.

I've been struggling with this, as we don't package alertify with the osweb bundle by default. We use this library to show the notifications and dialogs on the osweb demo page. Browsers do have such functionality natively as well, but these are blocking and that way stop the osweb event loop execution. So when you present users with a browser dialog such as 'are you sure you want to ....', or 'an error occurred' it breaks the experiment. Alertify works asynchronously (as it is completely implemented in JS), and does not have this problem.

Alertify is present on the osweb demo page, but that's because it is added separately later (or actually it is a dev bundle I see now). We might want to consider adding it to the production bundle as well, so we can show effective dialogs wherever osweb is used?

After this, it is very easy to show any errors in an alertify dialog.

**Comment by dschreij** [comment]
Fixed through b0c609db5801df1198847ad29e9c1ada0c9c40cb and 8fdaf102e4fff8026ad3bab0194c705d039bdd7a of dschreij/opensesame-extension-osweb
