### ISSUE TITLE
repeat_cycle freezes experiment when trying to repeat

### ISSUE THREAD

**Issue by smathot** [shyras/osweb#140]
When the repeat-if statement of a `repeat_cycle` item evaluates to `True`, the experiment freezes. It's unclear to me where the experiment hangs, i.e. if it's the `repeat_cycle` item itself or if it's the `loop` that chokes on the forced repetition. When the repeat-if statement evaluates to `False`, things work as expected, i.e. nothing happens.

You can easily test this by creating a `loop` with only one cycle and then adding a `repeat_cycle` item with 'always' as a repeat-if statement.

**Comment by dschreij** [comment]
This seriously is a tough nut to crack. The whole looping mechanism of osweb is so convoluted that I have no idea (yet) how this exactly is going wrong. I have come as far as understanding that the problem lies in `Loop._complete()` (https://github.com/shyras/osweb/blob/master/src/js/osweb/items/loop.js#L53-L70), which is called when the loop item concludes. When `repeat_cycle` is set to 1 by the repeat_cycle item, steps are made to repeat the cycle, but they (clearly) have no effect. Moreover, this also causes the steps in the `else` clause to be skipped, which make osweb move on to the next item, and thus it hangs...

The solution has to be made in the `if {}` block, in that it reruns the current cycle, but I have yet to find out how to make this work...

**Comment by dschreij** [comment]
I also think this way of implementing repeat_cycle is wrong in the first place. The repeat_cycle item should be evaluated 'in cycle' and not when a loop item has finished running...

**Comment by smathot** [comment]
So what do you propose? I don't think that this item is essential, so we could decide to remove it from the list of supported items? Or do you feel that it's doable?

>  The repeat_cycle item should be evaluated 'in cycle' and not when a loop item has finished running...

Agreed.

**Comment by dschreij** [comment]
I’m crunching on it now. Conceptually (outside of the osweb codebase) this appears to be a simple problem, so I think we should get this to work somehow.
Give me a small while and if it does take too long then we’ll move on to the next task and leave this as if for now.
