### ISSUE TITLE
Experiment Size and Error with JATOS

### ISSUE THREAD

**Issue by d-bohn** [shyras/osweb#160]
Hello,

I have created a simple image rating study using OSWeb. It works completely as expected offline, and when I convert the experiment to an OSWeb study, the compatibility check is fine. However, I do get an alert that my experiment is about twice as large as the recommend 10 MB, as I have quite a few images in the pool that I need to select a subset from randomly for participants to rate.

The study runs through fine on JATOS, however upon completing it (i.e., after the last page coded in Opensesame) I get a message that an error occurred ("A problem occurred:
Errors occurred during the experiment") and the "State" of the run is "FAIL". I can't seem to track down any additional information about why it failed. Out of curiosity I ran a version of the experiment with considerably less stimuli in the pool and this version was able to both run successfully and without an state errors. Is it possible that the size of the stimulus pool is causing some backend JATOS issues? If so, any suggestions on remedying the issue without having to reduce file pool size?

Opensesame version: 3.2.8
OSWeb version: 1.3.4.0
JATOS version: 3.4.1

**Comment by d-bohn** [comment]
I just ran the experiment on a local version of JATOS and it worked and finished as expected. So, I compared the output (from Opensesame) between the two, and it appears that the experiment hosted on the server is not recording every trial. On that file I see that it missed recording to the output 3 trials. Interestingly, these weren't consecutive trials, and appear to be randomly spaced out (110, 186, and 280 trials into the experiment out of 288 trials).

EDIT:
It appears that it might be a timing issue related to recording the data. When I re-tested the study hosted on the server and slowed down my response (750ms vs. 130ms per trial), every trial except one was recorded. Slowing down to ~1088ms per trial allowed for successful completion of the study. Interestingly, when I ran the experiment locally through JATOS I was averaging 120ms per trial without any recording issues.

**Comment by dschreij** [comment]
Hi Daniel,
I have experienced the same! Somehow JATOS does not pick up the data of every trial that OsWeb sends to it. I have also had a lot of occurrences of missing trials. I have currently programmed osweb in such a way that it sends over the collected data of a trial to Jatos directly after the trial. There's also an option to send over *all* data at once at the end of the experiment, but I didn't choose to do this, because it seemed less robust to me, and it overwrites all data on Jatos that has been sent to it up till then. Reconsidering, I now think is the best option, as osweb also keeps a local copy of the collected data which should never miss a trial. If the transfer of all data at the end of the experiment should fail, then the data already sent to Jatos should not be overwritten and you should still possess the data that has been sent after each trial (as in the current situation).

The probable reason for Jatos missing trials, and the difference in behavior you are seeing between different servers: We have found out in a different setting that Jatos needs a lot of resources to function correctly. We tried downloading 500+ datasets at once, and that was too much for it. We fixed this by doubling the resources of the VPS Jatos was running on, and then all worked fine again. In similar vein, your remote server may have less resources at its disposal than your local system on which you run Jatos, making it more prone to failure. Hopefully this behavior will get ironed out in the future by the Jatos team (or maybe already has in the 3.4.x releases which I haven't tried yet).

In any case, I plan on tackling the issue of missing trials at the start of next year, along with other overhauls of the osweb library. Hopefully you can work around the current behavior until then.

**Comment by d-bohn** [comment]
Hi Daniel.

Thanks for the response. I'm glad that this is a known issue and is not isolated to my experiences, despite being inconvenient.

From my understanding of your reply, aside from altering the OSWeb source code (which is obviously the best, long term fix), one potential temporary fix might be to use the copy of the data that OSWeb stores locally. If so, does OSWeb save it to the disk in an accessible area? Or is it to a temp file somewhere? If not, would it be possible to just add some javascript code at the end of the experiment to do this? Perhaps something similar to python's `log.write_vars()` where it will just write to the experiment directory in JATOS1 `study_assets_root`? I apologize I am not as familiar with javascript as I am with python. Thanks again!

**Comment by kristian-lange-tw** [comment]
Hi guys,

Let me try to explain this from JATOS' side. If I understand correctly OSWeb uses jatos.appendResultData to send its data back to JATOS after each trial. The problem here might be that jatos.js currently allows only one jatos.appendResultData at the time. If there is a second call before the previous call is finished (finished means here the HTTP request to the JATOS server got a response), the function just returns an error. This is only a problem if the JATOS server is very slow in responding - or if there are many jatos.appendResultData right after another. The latter might be the problem here. Each trial uses jatos.appendResultData, JATOS server doesn't response on time, trial's result data gets dropped. 

As Daniel suggested, OSWeb could use jatos.submitResultData (http://www.jatos.org/jatos.js-Reference.html#jatossubmitresultdata) to send all result data from all trials at once in the end of the experiment.

Another way is to let OSWeb wait until the request is done each time. jatos.js allows callbacks or jQuery's promises to accomplish that. E.g. with 'done' of jQuery it is `jatos.appendResultData(resultData).done(function-to-continue)` and this ensures that the jatos.appendResultData request was successful. But compared to the first solution this might slow down your experiment since OSWeb has to wait between each trial until JATOS gives a response. So I'd suggest using the first one.

And on the second issue, the downloading on many result data at once: this is resolved in the current release 3.4.1.

Best,
Kristian

**Comment by dschreij** [comment]
Hi Kristian!

Thanks for chiming in and confirming my suspicions with your knowledge! I am going to update Jatos soon on our server to version 3.4.2 (I tried doing so using the new auto-update service, but that didn't work an failed with a 502 error).
I also plan on working a bit on osweb soon and hope to change the way of storing data as you describe above. I hope the temporary lock that Jatos imposes (in that it has to wait for a previous request to return) is only for a single client and not between clients? If the latter is the case, that would be quite an architectural challenge to work around.

Best,

Daniel

**Comment by kristian-lange-tw** [comment]
Hi Daniel!

Correct, not between clients: many different workers can call jatos.submitResultData or appendResultData in parallel. Actually when I introduced this only-one-result-data-at-a-time I thought of it more like a feature, since it does enforce an order in the appended result data (result data send 1-2-3 will always be stored as 1-2-3 and never e.g. as 1-3-2), but I can see that it has a downside with many appendings in quick succession. 

I'm curious, can you tell me more about the failed auto-update attempt. Did you get any error messages in logs/application.log or logs/loader.log?

Best,
Kristian

**Comment by kristian-lange-tw** [comment]
Hi everyone, I'm not sure whether someone is working on this bug right now, but if not I would give it a try. It's just that people using OSWeb with JATOS getting frustrated by this. As far as I understand it's easily fixed in OSWeb's jatos.js, isn't it? I will do a pull request when done.

**Comment by smathot** [comment]
For reference: After discussion, we've decided that @kristian-lange-tw will resolve this issue primarily in JATOS, and if necessary we'll patch The OSWeb extension too.

**Comment by Eslifkin23** [comment]
@smathot or @kristian-lange-tw is this something that has been successfully resolved?  Or will this be resolved in the next JATOS update?  I'm still struggling with this particular issue.  Thanks!

**Comment by smathot** [comment]
It has been resolved, actually, in OSWeb 1.3.7. So I'm closing this!
