### ISSUE TITLE
Implement classes/response_info.js

### ISSUE THREAD

**Issue by dschreij** [shyras/osweb#24]
Class is defined but currently empty and unused. What is it intended for?

**Comment by shyras** [comment]
Is a copy of the response_info class in OpenSesame 3.1.1, has no functionality yet.

**Comment by smathot** [comment]
The way that response items work internally has changed quite a bit in 3.1. The `generic_response` class is gone, and there is now a `base_response_item`, which is much more systematic. But the 3.0 way works fine too, of course, so I wouldn't give this high priority, because it might be quite a bit of work.

**Comment by dschreij** [comment]
Related to https://github.com/shyras/osweb/issues/25. Both part of the same system
