### ISSUE TITLE
Large texts are not rendered correctly (likely bounding-box issue related to HTML)

### ISSUE THREAD

**Issue by smathot** [shyras/osweb#52]
When you draw a large chunk of text, it is often not rendered correctly; that is, there seems to be a bounding box that is too small, and the text that falls outside of this bounding box is not rendered correctly. It seems related to the use of HTML tags, including line breaks.

For example, a display that should look like:

![image](https://cloud.githubusercontent.com/assets/594936/19347953/cde292b6-914b-11e6-8486-d3b979508243.png)

Actually looks like:

![image](https://cloud.githubusercontent.com/assets/594936/19348013/0845c702-914c-11e6-9f88-b95b5cc4e8c7.png)

Here's the script for the experiment:

```

---
API: 2
OpenSesame: 3.1.3a10
Platform: posix

---
set width 1024
set uniform_coordinates yes
set title "New experiment"
set subject_parity even
set subject_nr 0
set start experiment
set sound_sample_size -16
set sound_freq 48000
set sound_channels 2
set sound_buf_size 1024
set round_decimals 2
set height 768
set fullscreen no
set form_clicks no
set foreground white
set font_underline no
set font_size 18
set font_italic no
set font_family mono
set font_bold no
set experiment_path "/home/sebastiaan/Tmp/opensesame"
set disable_garbage_collection yes
set description "The main experiment item"
set coordinates uniform
set compensation 0
set canvas_backend xpyriment
set bidi no
set background black

define sequence experiment
    set flush_keyboard yes
    set description "Runs a number of items in sequence"
    run welcome always

define sketchpad welcome
    set start_response_interval no
    set reset_variables no
    set duration keypress
    set description "Displays stimuli"
    draw textline center=1 color=white font_bold=no font_family=mono font_italic=no font_size=32 html=yes show_if=always text="Lorem ipsum dolor sit amet, consectetur<br />adipiscing elit, sed do eiusmod tempor<br />incididunt ut labore et dolore magna<br />aliqua. Ut enim ad minim veniam, quis<br />nostrud exercitation ullamco laboris<br />nisi ut aliquip ex ea commodo consequat." x=0 y=0 z_index=0
```

**Comment by dschreij** [comment]
I've spotted this too, and I've already spent quite some time trying to fix this. I know what causes this and I'm going to get a bit technical:

The problem is that to calculate the dimensions of the layer in which I want to render the text on the canvas, I have to first invisibly create this layer in the DOM. When rendered in the DOM, the layer uses the cogsci stylesheet (which is used to render the page). In this stylesheet, some general properties have likely been overwritten or specified with a *,  for example

``` css
* {
   line-height: 40px;
}
```

On the canvas however, all global style specifications are ignored and a clean isolated internal style sheet is used. So when I calculate the layer dimensions using the DOM, they are not appropriate for the layer as is is to rendered on the canvas.

I have to somehow either make sure the invisible layer in which pre-render the text to calculate its dimensions ignores the global stylesheet, or that the stylesheet in the canvas inherits from the global stylesheet (which is not preferable as I think it will probably cause a whole load of new problems). The new [scope attribute](https://css-tricks.com/saving-the-day-with-scoped-css/) may be of help, but I have not had the opportunity to play around with it yet.

**Comment by dschreij** [comment]
Another problem is that the HTML markup used in OpenSesame is often not valid XHTML markup, which throws off the 'real' HTML renderers in browsers.

**Comment by smathot** [comment]
> Another problem is that the HTML markup used in OpenSesame is often not valid XHTML markup, which throws off the 'real' HTML renderers in browsers.

Is this problem more easily fixed if you assume that the text is just regular HTML, rather than the bastardized dialect used in OpenSesame? If so, then I think it's fine to assume that text is regular HTML, and then file an issue on the main OpenSesame repo for better HTML support. What do you think? Better to improve OpenSesame than to unnecessarily cripple OSWeb.

Regarding the stylesheet problem. Would it be possible to create a special CSS class that uses only defaults and thus (I assume) matches the internal stylesheet used for the canvas? And then apply this CSS class to the dummy layer that you use to determine the dimensions. Or is that technically tricky to do?

**Comment by dschreij** [comment]
> Is this problem more easily fixed if you assume that the text is just regular HTML, rather than the bastardized dialect used in OpenSesame? If so, then I think it's fine to assume that text is regular HTML, and then file an issue on the main OpenSesame repo for better HTML support. What do you think? Better to improve OpenSesame than to unnecessarily cripple OSWeb.

I think I didn't express myself correctly here. The HTML provided by OpenSesame is processed without errors, but is often not interpreted as desired, causing discrepancies in how OpenSesame renders HTML and how it is rendered in the browser.

For instance, this is acceptable in OpenSesame, but doesn't work in browsers

``` html
<span color="red">This text should be red</span>
```

In OpenSesame this text will be displayed in red, as you intend to, but the color attribute is not conventional HTML. You can add any attributes that you want to tags, but the browser won't do anything with them. This is not the conventional way to specify the color of an element. The correct HTML way would be

``` html
<span style="color:red">This text should be red</span>
```

but this is not understood by OpenSesame (and even causes a crash!)

This point is not really relevant to this issue though and should maybe indeed be addressed somewhere else. 

The issue here is that the way the HTML is rendered in the invisible preview div is different from how it is rendered in the canvas.

> Regarding the stylesheet problem. Would it be possible to create a special CSS class that uses only defaults and thus (I assume) matches the internal stylesheet used for the canvas? And then apply this CSS class to the dummy layer that you use to determine the dimensions. Or is that technically tricky to do?

That would be a really good solution, but it is also where the core of the problem lies. There are not really default values for styles, or rather there are, but they differ vastly between browsers. Even though there is an official specification of these defaults, some organisations blatantly ignore these and this is especially a problem with some older versions of their browsers. 
There are some people and organisations who have attempted to write a cross browser css reset (for example [here](http://meyerweb.com/eric/tools/css/reset/) and [here](https://necolas.github.io/normalize.css/) ) which might do the trick (I think normalize.css is even a part of Bootstrap). I will give those a try soon in combination with the scoped styles.

**Comment by shyras** [comment]
With the current version the text is rendered correctly in html and non html mode.
