### ISSUE TITLE
Example experiments

### ISSUE THREAD

**Issue by dschreij** [shyras/osweb#86]
We should have a battery of example experiments. These should comprehensively use all supported functionality.

**Comment by dschreij** [comment]
@smathot Do you already have any idea what experiments would be representative for a test battery?

**Comment by smathot** [comment]
Yes, I do! Because I want to use those also for Introduction to Psychology as demo experiments. Right now I'm in Japan, and the list with experiments is in my office, but I remember that we wanted to have at least the following:

- An optimal viewing position (OVP) experiment, which is just a lexical decision task where the position of the word relative to the fixation dot is varied.
- A tilt-adaptation experiment, where the orientation of an adapter gabor is varied and participants have to indicate the orientation of a tester gabor.

There are a few more, but I'll get back to you on this. I'll also take care of the implementation so that it works on the desktop, taking into account the limitations of OSWeb.

**Comment by dschreij** [comment]
Alright! I'm a bit at a loss on what steps to take next. I mean, there is a lot of work to do, but how to determine the next steps in such a way that progress is measurable is a bit difficult.
I think I'm going to focus on writing tests, and try to untangle the modules as much as I can (without rewriting a lot).

Have fun in Japan!

**Comment by smathot** [comment]
All the example experiments that I had in mind have been implemented now!
