### ISSUE TITLE
Logger always logs all variables

### ISSUE THREAD

**Issue by smathot** [shyras/osweb#95]
If you disable the 'Automatically detect and log all variables' option in the logger, and then manually select a few variables to log, the logger nevertheless logs all variables. Being able to selectively log only a subset of variables is important to save bandwidth and respect the participants' privacy.

**Comment by dschreij** [comment]
I'm looking into this issue, and I'm a bit confused in the redesign of the logger item of OpenSesame. Does a user now have to manually list/type out the variables to be logged instead of selecting them from a long list with checkbox items?

As an aside, I would also suggest to use a trash can icon instead of a 'forbidden' icon to delete single items, but I can place this suggestion in an issue of the OpenSesame repo itself.

**Comment by dschreij** [comment]
To add to the confusion, this appears to work correctly for me in osweb. I disabled logging of all variables, then only entered `response_time` and `acc` as items to be logged. osweb then succesfully only prints these variables at the end of the experiment. I haven't tested this in combination with JATOS though, so maybe the problem lies in the communication with JATOS?

**Comment by smathot** [comment]
> I'm looking into this issue, and I'm a bit confused in the redesign of the logger item of OpenSesame. Does a user now have to manually list/type out the variables to be logged instead of selecting them from a long list with checkbox items?

The logic is that all detected variables are logged if 'Automatically detect and log all variables' is enabled. In addition, all variables that are explicitly added are logged, regardless of whether auto-detect is enabled. Does that make sense?

> To add to the confusion, this appears to work correctly for me in osweb. I disabled logging of all variables, then only entered response_time and acc as items to be logged. osweb then succesfully only prints these variables at the end of the experiment. I haven't tested this in combination with JATOS though, so maybe the problem lies in the communication with JATOS?

I remember that Jaap had hardcoded that only a few specific variables were printed, so that might be it. But I'll take a look at it.

**Comment by smathot** [comment]
You're right actually, it does work. Must have been some oversight on my part.
